package gitlet;

import java.io.File;
import java.io.Serializable;
import java.nio.charset.StandardCharsets;

import static gitlet.Repository.*;
import static gitlet.Utils.*;

/**
 * Represents a gitlet blob object.
 * Generated by 'add' operation, stored in files (in 'blobs' folder exactly).
 *
 * @author Siyuan Lu
 */
public class Blob implements Serializable {
    /** The contents of this Blob which is stored as bytes. */
    private byte[] contents;
    /**  The unique id of each Blob. */
    private String id;
    /** The filename of the Blob. */
    private String filename;

    /**
     * Constructs new blob as well as saves it to the file.
     *
     * @param nFilename filename of this new blob
     */
    public Blob(String nFilename) {
        File newFile = join(CWD, nFilename);
        this.filename = nFilename;
        if (newFile.length() != 0) {
            this.contents = readContents(newFile);
            this.id = sha1(filename, contents);
        } else {
            this.contents = null;
            this.id = sha1(filename);
        }
        File blobFile = join(BLOBS_DIR, this.id);
        if (!blobFile.exists()) {
            writeObject(blobFile, this);
        }
    }

    public byte[] getContents() {
        return contents;
    }

    public String getContentsAsString() {
        return new String(contents, StandardCharsets.UTF_8);
    }

    public String getFilename() {
        return filename;
    }

    public String getId() {
        return id;
    }
}
